services:
  app:
    build: .
    container_name: python_scraper_app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/scraperdb
    command: ["python", "main.py"]
    volumes:
      - .:/app

  mongo:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
